# Generated by Django 3.0.4 on 2020-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.TextField()),
                ('commentary_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('last_load_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalAuthorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('ons_la_name', models.TextField()),
                ('xr_la_name', models.TextField()),
                ('is_declared', models.BooleanField()),
                ('declaration_date', models.DateField()),
                ('target_net_zero_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.TextField()),
                ('is_political_org', models.BooleanField()),
                ('date_call_made', models.DateField()),
                ('target_net_zero_year', models.IntegerField()),
                ('earliest_year', models.IntegerField()),
                ('latest_year', models.IntegerField()),
                ('vote_pcnt', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField()),
                ('account_id', models.TextField()),
                ('date', models.DateField()),
                ('follows', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('follows_cum', models.IntegerField()),
                ('likes_cum', models.IntegerField()),
                ('views_cum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('date', models.DateField()),
                ('page_views', models.IntegerField()),
                ('sessions', models.IntegerField()),
            ],
        ),
    ]
