# Generated by Django 3.0.4 on 2020-03-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200321_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='id',
        ),
        migrations.AlterField(
            model_name='commentary',
            name='chart_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
