# Generated by Django 3.0.4 on 2020-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200321_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadhistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='loadhistory',
            name='table_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
