# Generated by Django 3.0.4 on 2020-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200321_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='follows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='follows_cum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='likes_cum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='views_cum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
