# Generated by Django 3.0.4 on 2020-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200321_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localauthorities',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
