# Generated by Django 3.0.4 on 2020-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200321_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localauthorities',
            name='target_net_zero_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
