# Generated by Django 3.0.4 on 2020-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200328_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='localauthorities',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
