# Generated by Django 3.0.4 on 2020-03-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_localauthorities_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localauthorities',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
