# Generated by Django 3.0.4 on 2020-04-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200330_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activists', models.IntegerField()),
            ],
        ),
    ]
