# Generated by Django 3.0.4 on 2020-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_actionnetwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionnetwork',
            old_name='activists',
            new_name='subscribed_activists',
        ),
        migrations.AddField(
            model_name='actionnetwork',
            name='unsubscribed_activists',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
