# Generated by Django 3.0.4 on 2020-05-17 06:59

from django.db import migrations, models

def insert_instagram_commentary(apps, schema_editor):
    Commentary = apps.get_model('commentary')

    instaCommentary = Commentary(
        chart_name='instagram',
        commentary_text='')

    instaCommentary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200413_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('follows', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(insert_instagram_commentary),
    ]
