# Generated by Django 3.0.4 on 2020-05-17 06:59

from django.db import migrations, models


def insert_instagram_commentary(apps, schema_editor):
    Commentary = apps.get_model('dashboard', 'commentary')

    instaCommentary = Commentary(
        chart_name='instagram',
        commentary_text='')

    instaCommentary.save()



class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_instagram'),
    ]

    operations = [
        migrations.RunPython(insert_instagram_commentary),
    ]
