# Generated by Django 3.0.4 on 2020-05-17 06:59

from django.db import migrations, models


def insert_commentary(apps, schema_editor):
    Commentary = apps.get_model('dashboard', 'commentary')

    commentary = Commentary(
        chart_name='action_network_activists',
        commentary_text='')

    commentary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_instagram2'),
    ]

    operations = [
        migrations.RunPython(insert_commentary),
    ]
