# Generated by Django 3.0.4 on 2020-05-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_actionnetwork2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionnetwork',
            old_name='subscribed_activists',
            new_name='cumulative',
        ),
        migrations.RenameField(
            model_name='actionnetwork',
            old_name='unsubscribed_activists',
            new_name='daily',
        ),
    ]
