# Generated by Django 3.0.4 on 2020-06-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200522_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram',
            old_name='follows',
            new_name='follows_cum',
        ),
    ]
