# Generated by Django 3.0.4 on 2020-07-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='localauthorities',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
